/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.12"
;
const char *compilation_string = "mipsel-uclibc-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I ../md5 -DBCMWPA2";
const char *link_string = "mipsel-uclibc-gcc -DBCMWPA2 gen-md5.o ../lib/libgnu.a ../md5/libmd5.a";
